// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['objects/Player'], function(Player) {
    var Player1;
    return Player1 = (function(_super) {
      __extends(Player1, _super);

      function Player1() {
        this.user_id = 1;
        this.name = 'player1';
      }

      Player1.prototype.update = function() {};

      return Player1;

    })(Player);
  });

}).call(this);
