// Generated by CoffeeScript 1.7.1
(function() {
  define(function() {
    var Time;
    return Time = (function() {
      function Time() {}

      Time.Now = function() {
        return (new Date()).getTime();
      };

      Time.Delay = function(s, f) {
        return setTimeout(f, s);
      };

      Time.Interval = function(s, f) {
        return setInterval(f, s);
      };

      return Time;

    })();
  });

}).call(this);
