// Generated by CoffeeScript 1.7.1
(function() {
  requirejs.config({
    baseUrl: 'behaviors'
  });

  require(['./Engine', 'objects/Test'], function(Engine, Test) {
    var engine;
    engine = new Engine({
      canvas_id: 'main'
    });
    engine.Bind(new Test);
    return engine.Run();
  });

}).call(this);
