// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['components/Behavior', 'lib/Collada', 'objects/Player', 'objects/Monster', 'objects/Wall'], function(Behavior, Collada, Player, Monster, Wall) {
    var Game;
    return Game = (function(_super) {
      __extends(Game, _super);

      function Game() {
        return Game.__super__.constructor.apply(this, arguments);
      }

      Game.prototype.Start = function(engine, cb) {
        return Collada.LoadModel('models/map1/map1.json', cb, function(mesh) {
          var inst, obj;
          switch (mesh.renderer.mesh_name) {
            case 'player1':
              obj = Player;
              break;
            case 'player2':
              obj = Monster;
              break;
            case 'wall':
              obj = Wall;
              break;
            default:
              engine.Log("cannot load mesh " + mesh.renderer.mesh_name + ": corresponding game object not implemented.");
              return;
          }
          obj.prototype.renderer = mesh.renderer;
          inst = new obj;
          obj.prototype.renderer.object = inst;
          return engine.Bind(inst);
        });
      };

      return Game;

    })(Behavior);
  });

}).call(this);
