// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['components/Behavior', 'components/Transform', 'components/SegmentCollider'], function(Behavior, Transform, SegmentCollider) {
    var Wall;
    return Wall = (function(_super) {
      __extends(Wall, _super);

      function Wall() {
        Wall.__super__.constructor.apply(this, arguments);
        this.transform = new Transform({
          object: this
        });
      }

      Wall.prototype.Start = function() {};

      Wall.prototype.Update = function() {};

      return Wall;

    })(Behavior);
  });

}).call(this);
