// Generated by CoffeeScript 1.7.1
(function() {
  requirejs.config({
    baseUrl: 'behaviors'
  });

  require(['./Engine', 'objects/Cube', 'objects/World'], function(Engine, Cube, World) {
    var c2, engine;
    engine = new Engine({
      canvas_id: 'main'
    });
    engine.Bind(new Cube);
    c2 = new Cube;
    c2.transform.position.x = 200;
    engine.Bind(c2);
    return engine.Run();
  });

}).call(this);
