// Generated by CoffeeScript 1.7.1
(function() {
  requirejs.config({
    baseUrl: 'behaviors'
  });

  require(['./Engine', 'objects/Game'], function(Engine, Game) {
    var engine;
    engine = new Engine({
      canvas_id: 'main'
    });
    engine.Bind(new Game);
    return engine.Run();
  });

}).call(this);
