// Generated by CoffeeScript 1.7.1
(function() {
  define(['engine.io-client/engine.io'], function(eio) {
    var Network;
    return Network = (function() {
      function Network() {}

      Network.prototype.connect = function() {
        var address, myid, socket;
        myid = null;
        address = window.location.href.split('/')[2].split(':')[0];
        socket = new eio.Socket('ws://' + address + '/');
        return socket.on('open', function() {
          socket.on('message', function(data) {
            var player_name, whoami, x, y, _ref;
            console.log(data);
            data = JSON.parse(data);
            if (data.player != null) {
              whoami = data.player.name;
              return myid = data.player.id;
            } else if (data.pm != null) {
              _ref = data.pm, player_name = _ref[0], x = _ref[1], y = _ref[2];
              objects[player_name].x = x;
              return objects[player_name].y = y;
            }
          });
          return socket.on('close', function() {});
        });
      };

      return Network;

    })();
  });

}).call(this);
