// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['components/Behavior'], function(Behavior) {
    var Script;
    return Script = (function(_super) {
      __extends(Script, _super);

      function Script(_arg) {
        this.object = _arg.object;
        Script.__super__.constructor.apply(this, arguments);
      }

      return Script;

    })(Behavior);
  });

}).call(this);
