// Generated by CoffeeScript 1.7.1
(function() {
  define(function() {
    var Canvas2D;
    return Canvas2D = (function() {
      function Canvas2D(_arg) {
        this.id = _arg.id;
        this.fps = 40;
        this.canvas = document.getElementById(this.id);
        this.ctx = this.canvas.getContext('2d');
        this.pixelBuf = void 0;
      }

      Canvas2D.prototype.Clear = function() {
        return this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
      };

      Canvas2D.prototype.DrawPixel = function(x, y, r, g, b, a) {
        var index;
        index = (x + y * this.canvas.width) * 4;
        this.pixelBuf.data[index + 0] = r;
        this.pixelBuf.data[index + 1] = g;
        this.pixelBuf.data[index + 2] = b;
        return this.pixelBuf.data[index + 3] = a;
      };

      Canvas2D.prototype.UpdateCanvas = function() {
        return this.ctx.putImageData(this.pixelBuf, 0, 0);
      };

      return Canvas2D;

    })();
  });

}).call(this);
