// Generated by CoffeeScript 1.7.1
(function() {
  var Point, Segment;

  define({
    Point: Point = (function() {
      function Point(x, y) {
        this.x = x;
        this.y = y;
      }

      return Point;

    })(),
    Segment: Segment = (function() {
      function Segment(p1, p2, d) {
        this.p1 = p1;
        this.p2 = p2;
        this.d = d;
      }

      return Segment;

    })()
  });

}).call(this);
