// Generated by CoffeeScript 1.7.1
(function() {
  define(function() {
    var GMath;
    return GMath = (function() {
      function GMath() {}

      GMath.rand = function(m, x) {
        return Math.round(Math.random() * (x - m)) + m;
      };

      GMath.clamp = function(value, min, max) {
        if (value > max) {
          return max;
        } else if (value < min) {
          return min;
        } else {
          return value;
        }
      };

      GMath.oscillate = function(amplitude, period, x0, time) {
        return amplitude * Math.sin(time * 2 * Math.PI / period) + x0;
      };

      return GMath;

    })();
  });

}).call(this);
