// Generated by CoffeeScript 1.7.1
(function() {
  define(function() {
    var Behavior;
    return Behavior = (function() {
      function Behavior() {
        this.enabled = true;
        this.renderer || (this.renderer = null);
        this.transform = null;
        this.scripts = {};
      }

      Behavior.prototype.BindScript = function(cls) {
        return this.scripts[cls.name] = new cls({
          object: this
        });
      };

      return Behavior;

    })();
  });

}).call(this);
