// Generated by CoffeeScript 1.7.1
(function() {
  define(function() {
    var Math;
    return Math = (function() {
      function Math() {}

      Math.rand = function(m, x) {
        return Math.round(Math.random() * (x - m)) + m;
      };

      return Math;

    })();
  });

}).call(this);
