// Generated by CoffeeScript 1.7.1
(function() {
  define(function() {
    var BoxCollider;
    return BoxCollider = (function() {
      function BoxCollider() {
        this.is_trigger = false;
        this.center = {
          x: 0,
          y: 0,
          z: 0
        };
        this.size = {
          x: 0,
          y: 0,
          z: 0
        };
      }

      BoxCollider.collidesWith = function(a, b) {
        var aT, bT, i, ii, nil, _i, _j, _len, _len1, _ref, _ref1;
        _ref = a.vertices;
        for (i = _i = 0, _len = _ref.length; _i < _len; i = _i += 3) {
          nil = _ref[i];
          aT = [
            {
              x: a.vertices[i].x + a.x + a.xT,
              y: a.vertices[i].y + a.y + a.yT
            }, {
              x: a.vertices[i + 1].x + a.x + a.xT,
              y: a.vertices[i + 1].y + a.y + a.yT
            }, {
              x: a.vertices[i + 2].x + a.x + a.xT,
              y: a.vertices[i + 2].y + a.y + a.yT
            }
          ];
          _ref1 = b.vertices;
          for (ii = _j = 0, _len1 = _ref1.length; _j < _len1; ii = _j += 3) {
            nil = _ref1[ii];
            bT = [
              {
                x: b.vertices[ii].x + b.y,
                y: b.vertices[ii].y + b.y
              }, {
                x: b.vertices[ii + 1].x + b.x,
                y: b.vertices[ii + 1].y + b.y
              }, {
                x: b.vertices[ii + 2].x + b.x,
                y: b.vertices[ii + 2].y + b.y
              }
            ];
            if (trianglesIntersect(aT, bT)) {
              return true;
            }
          }
        }
        return false;
      };

      BoxCollider.trianglesIntersect = function(a, b) {
        var l1x, l1y, l2x, l2y, r1x, r1y, r2x, r2y;
        l1x = Math.min(a[0].x, a[1].x, a[2].x);
        r1x = Math.max(a[0].x, a[1].x, a[2].x);
        l1y = Math.max(a[0].y, a[1].y, a[2].y);
        r1y = Math.min(a[0].y, a[1].y, a[2].y);
        l2x = Math.min(b[0].x, b[1].x, b[2].x);
        r2x = Math.max(b[0].x, b[1].x, b[2].x);
        l2y = Math.max(b[0].y, b[1].y, b[2].y);
        r2y = Math.min(b[0].y, b[1].y, b[2].y);
        if (l1x > r2x || l2x > r1x) {
          return false;
        }
        if (l1y < r2y || l2y < r1y) {
          return false;
        }
        return true;
      };

      return BoxCollider;

    })();
  });

}).call(this);
