// Generated by CoffeeScript 1.7.1
(function() {
  define(['../lib/Vector3'], function(Vector3) {
    var Transform;
    return Transform = (function() {
      function Transform(_arg) {
        this.parent = _arg.parent;
        this.position = new Vector3;
        this.rotation = new Vector3;
        this.lossyScale = new Vector3;
        this.localPosition = new Vector3;
        this.localRotation = new Vector3;
        this.localScale = new Vector3;
      }

      Transform.prototype.Translate = function(vec3) {};

      Transform.prototype.Rotate = function(vec3) {};

      return Transform;

    })();
  });

}).call(this);
