// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['components/Script', 'lib/Vector3', 'lib/GMath'], function(Script, Vector3, GMath) {
    var AutoPilot;
    return AutoPilot = (function(_super) {
      __extends(AutoPilot, _super);

      function AutoPilot() {
        return AutoPilot.__super__.constructor.apply(this, arguments);
      }

      AutoPilot.prototype.Update = function(engine) {
        var x, y;
        x = engine.deltaTime * GMath.oscillate(373, 5 / 2, 0, engine.time);
        y = engine.deltaTime * GMath.oscillate(411, 5, 0, engine.time);
        return this.object.collider.Move(engine, new Vector3(x, y, 0));
      };

      return AutoPilot;

    })(Script);
  });

}).call(this);
