// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['components/Script', 'lib/Input'], function(Script, Input) {
    var CurrentPlayerPlayer;
    return CurrentPlayerPlayer = (function(_super) {
      __extends(CurrentPlayerPlayer, _super);

      function CurrentPlayerPlayer() {
        return CurrentPlayerPlayer.__super__.constructor.apply(this, arguments);
      }

      CurrentPlayerPlayer.prototype.OnControllerColliderHit = function(engine, collidingObject) {
        if (this.object.constructor.name === 'Player' && collidingObject.constructor.name === 'Monster') {
          if (collidingObject.visible) {
            alert('You were caught by the seeker! You LOOSE!');
            return location.reload();
          } else {
            return console.log('eerie breathing is heard');
          }
        }
      };

      CurrentPlayerPlayer.prototype.Update = function(engine) {
        if (Input.GetButtonDown('Fire')) {
          console.log('interact');
        }
        if (Input.GetButtonDown('Alt Fire')) {
          console.log('toggle flashlight');
          return this.object.ToggleFlashlight();
        }
      };

      CurrentPlayerPlayer.prototype.DrawGUI = function(engine) {
        engine.Info('Controls: LClick - Interact, RClick - toggle light', 50, 'red', 12);
        return engine.Info('Objective: Sneak and hide from the seeker', 51, 'gray', 12);
      };

      return CurrentPlayerPlayer;

    })(Script);
  });

}).call(this);
